### ISSUE TITLE
What is data_cfg.yaml in infer.py

### ISSUE THREAD

**Issue by abcd40404** [TiagoCortinhal/SalsaNext#16]
I want to infer semantic-kitti dataset with pre-trained model.
When I run eval.sh, it required data_cfg.yaml. What information should I provide to run this code successfully?
BTW, I use salsanext.yml as arch_cfg.yaml, is that correct?

Thank you!

**Comment by shinya7y** [comment]
Doesn't this work?
https://github.com/TiagoCortinhal/SalsaNext/blob/master/train/tasks/semantic/config/labels/semantic-kitti.yaml

**Comment by TiagoCortinhal** [comment]
> Doesn't this work?
> https://github.com/TiagoCortinhal/SalsaNext/blob/master/train/tasks/semantic/config/labels/semantic-kitti.yaml

Hello @abcd40404, as @shinya7y said, data_cfg.yaml is the configuration for the dataset (labels, colours for the classes, train/valid/test splits, etc).

Arch_cfg.yaml is related to the arch which is salsanext.yml yes.
