### ISSUE TITLE
ModuleNotFoundError: No module named 'tasks.semantic.modules.ConcreteDropout'

### ISSUE THREAD

**Issue by chowkamlee81** [TiagoCortinhal/SalsaNext#5]
@TiagoCortinhal , iam getting error below. Kindly help

File "../../tasks/semantic/modules/trainer.py", line 20, in <module>
    from tasks.semantic.modules.SalsaNext import *
  File "../../tasks/semantic/modules/SalsaNext.py", line 9, in <module>
    from tasks.semantic.modules.ConcreteDropout import ConcreteDropoutConvolutional
ModuleNotFoundError: No module named 'tasks.semantic.modules.ConcreteDropout'

**Comment by TiagoCortinhal** [comment]
Hello @chowkamlee81!

Thank you for pointing this out. We recently moved from ConcreteDropout to another way of computing the uncertainties (https://github.com/uzh-rpg/deep_uncertainty_estimation) and I forgot to remove the import. I pushed the correction.

You also can simply go to the SalsaNext.py and remove it manually.


Best!
