### ISSUE TITLE
ModuleNotFoundError: No module named 'tasks.semantic.modules.SalsaNextUncertainty'

### ISSUE THREAD

**Issue by chowkamlee81** [TiagoCortinhal/SalsaNext#6]
I started training by executing train.py along with command line arguments but i got error below

ModuleNotFoundError: No module named 'tasks.semantic.modules.SalsaNextUncertainty'

Kindly help

**Comment by TiagoCortinhal** [comment]
Hey!

Again old class names relating to the Dropout. I tested and it seems fixed!


Let me know if something still doesn't work!

**Comment by chowkamlee81** [comment]
Still aim getting the smae error below as i copied your recent changes. Kindly help

  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tasks.semantic.modules.SalsaNextUncertainty'

**Comment by chowkamlee81** [comment]
Sorry didn't copy exactly. Closing the issue
