### ISSUE TITLE
Error trying to train from pre-trained weights ''Missing key(s) in state_dict:''

### ISSUE THREAD

**Issue by DavideCoppola97** [TiagoCortinhal/SalsaNext#65]
Hi, when I try to start a training using the weights you published I get this error:
Trying to train from scratch on the other hand, everything seems to be fine
The platform is Windows 10 with Anaconda
I have made sure that the directory is right and in fact the SalsaNext file is correctly opened, however it continues to generate this error, as if expecting something different in the content, it seems that the modules are all there, however the script expects to find only the module names while in the file there is the suffix '.module'
![Cattura](https://user-images.githubusercontent.com/63714542/137719776-a63fca1f-e39f-4acf-86a4-356d8f8d3834.JPG)
![Cattura2](https://user-images.githubusercontent.com/63714542/137720629-ef18f2aa-48a3-4023-909d-9491ce5cdb55.JPG)

**Comment by FUTUREEEEEE** [comment]
simply Comment out this line 
https://github.com/Halmstad-University/SalsaNext/blob/a02fad97d646d4c132266ab79fbaea3ecfc237ed/train/tasks/semantic/modules/user.py#L66
