### ISSUE TITLE
Errors occur during training.

### ISSUE THREAD

**Issue by LiXiang0021** [TiagoCortinhal/SalsaNext#71]
Thanks for author's remarkable working!

when i start to train this network without pretrained model, this error occurs showing below.
Can someone help me, thanks a lot!

/media/lijianguo/data_ssd/coding_test_platfrom/SalsaNext-master/train/tasks/semantic$ python3 train.py -d /media/lijianguo/data_ssd/kittidata/SemanticKITTI/data/dataset -ac /media/lijianguo/data_ssd/coding_test_platfrom/SalsaNext-master/salsanext.yml -l /media/lijianguo/data_ssd/coding_test_platfrom/SalsaNext-master/train_logs 
INTERFACE:
dataset /media/lijianguo/data_ssd/kittidata/SemanticKITTI/data/dataset
arch_cfg /media/lijianguo/data_ssd/coding_test_platfrom/SalsaNext-master/salsanext.yml
data_cfg config/labels/semantic-kitti.yaml
uncertainty False
Total of Trainable Parameters: 6.71M
log /media/lijianguo/data_ssd/coding_test_platfrom/SalsaNext-master/train_logs/logs/2022-4-01-18:46
pretrained None

Opening arch config file /media/lijianguo/data_ssd/coding_test_platfrom/SalsaNext-master/salsanext.yml
Opening data config file config/labels/semantic-kitti.yaml
Not creating new log file. Using pretrained directory
No pretrained directory found.
Copying files to None for further reference.
unsupported operand type(s) for +: 'NoneType' and 'str'
Error copying files, check permissions. Exiting...

**Comment by AgentWizardX** [comment]
Good morning, were you able to solve this @LiXiang0021 ?

**Comment by LiXiang0021** [comment]
Thanks for your reply and I had solved it.

**Comment by AgentWizardX** [comment]
@LiXiang0021 How should I go about getting a log folder to be created or even recognize the pretrained directory?

**Comment by TiagoCortinhal** [comment]
> @LiXiang0021 How should I go about getting a log folder to be created or even recognize the pretrained directory?

-l for the log -p for the pretrained

**Comment by rohithsaro** [comment]
> Thanks for your reply and I had solved it.

@LiXiang0021 
Could you provide the solution ?

**Comment by TiagoCortinhal** [comment]
Due to inactivity
