### ISSUE TITLE
Pretrained model dead link

### ISSUE THREAD

**Issue by DeviRajendra** [TiagoCortinhal/SalsaNext#73]
Hi, I am trying to access the pre-trained model link that is mentioned on your repository, but I am encountering an issue where I cannot access the file.  I have tried multiple times but the same result. Could you please provide guidance on how I can access the pre-trained model? Thank you for your help.

**Comment by TiagoCortinhal** [comment]
Hello,

The [https://drive.google.com/file/d/10fxIwPK10UVVB9jsgXDZSDwj4vy9MyTl/view](link) works for me. What issue are you encountering?

**Comment by DeviRajendra** [comment]
Hi,

Able to access now. Earlier it was showing error while access the link.

Thanks
