### ISSUE TITLE
Link for pretrained model is expired

### ISSUE THREAD

**Issue by binyang97** [TiagoCortinhal/SalsaNext#82]
Hello,

I cannot download the pretrained weights from the link provided. It turns out the data is no more accessible. Can you fix it?

Thanks!

Best,
Bin

**Comment by TiagoCortinhal** [comment]
Hello,

I have updated the link on the README. [Here it is the new one](https://drive.google.com/file/d/1utfzooTDAlV5M6XGvCE0-L-vbdLe_2rD/view)

Best 
Tiago

**Comment by paprays** [comment]
Could you please grant access to the Google Drive so I can download [The new one](https://drive.google.com/file/d/1utfzooTDAlV5M6XGvCE0-L-vbdLe_2rD/view) ? Thank you!
