### ISSUE TITLE
Can not find function `resize2D_as`

### ISSUE THREAD

**Issue by EthanZhangYi** [TiagoCortinhal/SalsaNext#9]
https://github.com/TiagoCortinhal/SalsaNext/blob/f67cc27ece3b37b8b8e3f305d813e5a0faeef4d1/train/tasks/semantic/modules/adf.py#L379-L380

**Comment by TiagoCortinhal** [comment]
Hey @EthanZhangYi thanks for pointing it out. 

I added the missing function.
